services:
  - type: web
    name: my-django-polls
    env: python
    buildCommand: "./build.sh"
    startCommand: |
      python manage.py migrate
      python manage.py loaddata polls/fixtures/exam_questions.json
      gunicorn pollapp.wsgi:application
