services:
  - type: web
    name: my-django-polls
    env: python
    buildCommand: "./manage.py collectstatic --noinput"
    startCommand: "gunicorn pollapp.wsgi:application"
    preDeployCommand: "./manage.py migrate && ./manage.py loaddata exam_questions.json"
