# Generated by Django 5.2.3 on 2025-07-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='mode',
            field=models.CharField(choices=[('EXAM', 'Exam'), ('SURVEY', 'Survey')], default='SURVEY', max_length=10),
        ),
    ]
